const stashProp = {
  ownerNames: "",
  picture: "",
  stashName: "",
  desc: "",
  SerialNum: "",
  date: "",
  timePosted: "",
  rewardEligibility: false,
  priorityStatus: [true, false],
  lastKLoc: "",
  imageAddress: "",
}
let date = new Date(Date.now()).toLocaleDateString();
let time = new Date(Date.now()).toLocaleTimeString()
const newItem = {
  userID: '',
  itemID: '',
  itemName: '',
  itemDesc: '',
  barCodeNum: '',
  s_p_Number: '',
  category: 'Select options',
  lost: false,
  reporterID: '',
  rewardEligibility: false,
  imageurl: '',
  priorityStatus: 'High-priority',
  dateAdded: date,
  timeAdded: time
}

const items = [
  {
    ownerNames: "John Doe",
    picture: "https://example.com/image1.jpg",
    stashName: "Lost Wallet",
    desc: "Black leather wallet containing ID and credit cards.",
    SerialNum: "12345A",
    date: "2024-11-01",
    timePosted: "10:30 AM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Central Park, NY",
    imageAddress: "/images/wallet1.jpg",
  },
  {
    ownerNames: "Jane Smith",
    picture: "https://example.com/image2.jpg",
    stashName: "Keys",
    desc: "A bunch of keys with a red keychain.",
    SerialNum: "67890B",
    date: "2024-11-02",
    timePosted: "11:00 AM",
    rewardEligibility: false,
    priorityStatus: "Medium",
    lastKLoc: "Times Square, NY",
    imageAddress: "/images/keys.jpg",
  },
  {
    ownerNames: "Sam Wilson",
    picture: "https://example.com/image3.jpg",
    stashName: "Smartphone",
    desc: "Black Samsung Galaxy S21 with a cracked screen.",
    SerialNum: "11223C",
    date: "2024-11-03",
    timePosted: "9:45 AM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Subway Station, NY",
    imageAddress: "/images/phone1.jpg",
  },
  {
    ownerNames: "Emily Davis",
    picture: "https://example.com/image4.jpg",
    stashName: "Laptop Bag",
    desc: "Grey laptop bag with Dell logo.",
    SerialNum: "44556D",
    date: "2024-11-04",
    timePosted: "12:15 PM",
    rewardEligibility: true,
    priorityStatus: "Low",
    lastKLoc: "Library, NY",
    imageAddress: "/images/laptop.jpg",
  },
  {
    ownerNames: "Michael Brown",
    picture: "https://example.com/image5.jpg",
    stashName: "Headphones",
    desc: "Over-ear black Sony headphones.",
    SerialNum: "77889E",
    date: "2024-11-05",
    timePosted: "2:30 PM",
    rewardEligibility: false,
    priorityStatus: "Medium",
    lastKLoc: "Coffee Shop, NY",
    imageAddress: "/images/headphones.jpg",
  },
  {
    ownerNames: "Sophia Turner",
    picture: "https://example.com/image6.jpg",
    stashName: "Wristwatch",
    desc: "Silver analog wristwatch.",
    SerialNum: "99001F",
    date: "2024-11-06",
    timePosted: "8:00 AM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Gym Locker, NY",
    imageAddress: "/images/watch.jpg",
  },
  {
    ownerNames: "Liam Johnson",
    picture: "https://example.com/image7.jpg",
    stashName: "Backpack",
    desc: "Black North Face backpack.",
    SerialNum: "33444G",
    date: "2024-11-07",
    timePosted: "1:00 PM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Bus Stop, NY",
    imageAddress: "/images/backpack.jpg",
  },
  {
    ownerNames: "Olivia Martin",
    picture: "https://example.com/image8.jpg",
    stashName: "Umbrella",
    desc: "Blue foldable umbrella.",
    SerialNum: "55566H",
    date: "2024-11-08",
    timePosted: "10:15 AM",
    rewardEligibility: false,
    priorityStatus: "Low",
    lastKLoc: "Restaurant, NY",
    imageAddress: "/images/umbrella.jpg",
  },
  {
    ownerNames: "William Evans",
    picture: "https://example.com/image9.jpg",
    stashName: "Sunglasses",
    desc: "Black Ray-Ban sunglasses.",
    SerialNum: "77881I",
    date: "2024-11-09",
    timePosted: "11:45 AM",
    rewardEligibility: true,
    priorityStatus: "Medium",
    lastKLoc: "Park Bench, NY",
    imageAddress: "/images/sunglasses.jpg",
  },
  {
    ownerNames: "Isabella Thomas",
    picture: "https://example.com/image10.jpg",
    stashName: "Earrings",
    desc: "Gold hoop earrings.",
    SerialNum: "99022J",
    date: "2024-11-10",
    timePosted: "3:00 PM",
    rewardEligibility: false,
    priorityStatus: "Low",
    lastKLoc: "Mall, NY",
    imageAddress: "/images/earrings.jpg",
  },
  {
    ownerNames: "James Walker",
    picture: "https://example.com/image11.jpg",
    stashName: "Passport",
    desc: "USA passport with a black cover.",
    SerialNum: "22333K",
    date: "2024-11-11",
    timePosted: "5:45 PM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Airport Terminal, NY",
    imageAddress: "/images/passport.jpg",
  },
  {
    ownerNames: "Mia Harris",
    picture: "https://example.com/image12.jpg",
    stashName: "Notebook",
    desc: "Spiral notebook with math notes.",
    SerialNum: "44555L",
    date: "2024-11-12",
    timePosted: "4:30 PM",
    rewardEligibility: false,
    priorityStatus: "Low",
    lastKLoc: "Classroom, NY",
    imageAddress: "/images/notebook.jpg",
  },
  {
    ownerNames: "Benjamin Clark",
    picture: "https://example.com/image13.jpg",
    stashName: "Camera",
    desc: "Canon DSLR camera.",
    SerialNum: "66777M",
    date: "2024-11-13",
    timePosted: "2:15 PM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Beach, NY",
    imageAddress: "/images/camera.jpg",
  },
  {
    ownerNames: "Charlotte Lee",
    picture: "https://example.com/image14.jpg",
    stashName: "Shoes",
    desc: "White Nike running shoes.",
    SerialNum: "88999N",
    date: "2024-11-14",
    timePosted: "1:30 PM",
    rewardEligibility: false,
    priorityStatus: "Medium",
    lastKLoc: "Gym, NY",
    imageAddress: "/images/shoes.jpg",
  },
  {
    ownerNames: "Lucas Scott",
    picture: "https://example.com/image15.jpg",
    stashName: "Tablet",
    desc: "iPad Air with a blue case.",
    SerialNum: "00112O",
    date: "2024-11-15",
    timePosted: "6:00 PM",
    rewardEligibility: true,
    priorityStatus: "High",
    lastKLoc: "Train Station, NY",
    imageAddress: "/images/tablet.jpg",
  },
];

export {stashProp, items, newItem};